### ISSUE TITLE
[REPL]: currently crashing frontend

### ISSUE THREAD

**Issue by martin-henz** [source-academy/modules#284]
The repl module is currently crashing. Example:
https://share.sourceacademy.org/p90gd

```
import { set_evaluator } from "repl";
```

**Comment by Cloud7050** [comment]
```
Unexpected Application Error!
Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ol (https://sourceacademy.org/static/js/main.fe43b29c.js:124:1842831)
    at e (https://sourceacademy.org/static/js/main.fe43b29c.js:124:1786947)
    at Cs (https://sourceacademy.org/static/js/main.fe43b29c.js:124:1799097)
    at Sc (https://sourceacademy.org/static/js/main.fe43b29c.js:124:1848023)
    at bl (https://sourceacademy.org/static/js/main.fe43b29c.js:124:1835302)
    at _l (https://sourceacademy.org/static/js/main.fe43b29c.js:124:1835230)
    at vl (https://sourceacademy.org/static/js/main.fe43b29c.js:124:1835093)
    at ol (https://sourceacademy.org/static/js/main.fe43b29c.js:124:1831873)
    at ll (https://sourceacademy.org/static/js/main.fe43b29c.js:124:1832264)
    at Hi (https://sourceacademy.org/static/js/main.fe43b29c.js:124:1772804)
    at https://sourceacademy.org/static/js/main.fe43b29c.js:124:1829806
```
https://react.dev/errors/130?invariant=130&args%5B%5D=undefined&args%5B%5D=

> The full text of the error you just encountered is:
> ```Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.[missing argument]```

**Comment by martin-henz** [comment]
Fixed by https://github.com/source-academy/modules/pull/301
